include topdir.mk
#_______________________________________________________________________________
#                                                                   IGNORE ABOVE
TARGET         = <auto>
SOURCES        = <auto>
SUBPROJS       =
SUBDIRS        =

EXTRA_MACROS   =
EXTRA_INCS     =
EXTRA_LIBDIRS  =
EXTRA_LIBS     =
EXTRA_CPPFLAGS =
EXTRA_LDFLAGS  =
EXTRA_ARFLAGS  =

#_______________________________________________________________________________
#                                                                   IGNORE BELOW
include $(TOPDIR)config.mk
